# needed to securely identify the workflow
name: autofix.ci

on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

permissions:
  contents: read

jobs:
  code:
    name: 🤖 Autofix code
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: voidzero-dev/setup-vp@a03302daa50cf2f017c8c7345730c2740df207d6 # v1
        with:
          node-version: lts/*
          cache: true

      - name: 🎨 Check for non-RTL/non-a11y CSS classes
        run: vp run lint:css

      - name: 🌐 Compare translations
        run: vp run i18n:check

      - name: 🌍 Update lunaria data
        run: vp run build:lunaria

      - name: 🔠 Fix lint errors
        run: vp run lint:fix

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # 635ffb0c9798bd160680f18fd73371e355b85f27
